version: "3.0"

volumes:
  openpokemon_main_module_data:
    driver: local
  openpokemon_vgc_module_data:
    driver: local

services:
  service-discovery:
    image: springcloud/eureka:latest
    ports:
      - "8761:8761"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  main-module-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=20000'
    volumes:
      - openpokemon_main_module_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openpokemon_main_db
      - POSTGRES_USER=PokeAdmin
      - POSTGRES_PASSWORD=toxtricity1996
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  vgc-module-db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    command: postgres -c 'max_connections=20000'
    volumes:
      - openpokemon_vgc_module_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=openpokemon_vgc_db
      - POSTGRES_USER=PokeAdmin
      - POSTGRES_PASSWORD=toxtricity1996
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"